LETTER_FOLDER=../letters/м
LETTER_WIP=$LETTER_FOLDER/letter_wip.xml
LETTER_AFTER=$LETTER_FOLDER/letter_after.xml
AFTER_LINTING=$LETTER_FOLDER/after_linting.xml

python3 python_script.py $LETTER_WIP $LETTER_AFTER

export XMLLINT_INDENT=$'\t'
xmllint --format - < $LETTER_AFTER > $AFTER_LINTING
rm $LETTER_AFTER
mv $AFTER_LINTING $LETTER_AFTER

ksdiff $LETTER_WIP $LETTER_AFTER
